"""
/api/explain endpoint.

Given a board position (FEN) and a move (UCI format), returns the
engine's evaluation, principal variation, and a plain-English
explanation of why the engine considers it a good move.

The explanation is generated by an LLM from the engine's evaluation
and principal variation, and cached per (position, move) to avoid
repeat API calls.
"""

from __future__ import annotations

import os

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from . import cache
from .llm_client import LLMConfigError, LLMRequestError, generate_text
from .notation import pv_to_san, score_to_readable, uci_move_to_san
from .prompts import SYSTEM_PROMPT, build_explanation_prompt
from .uci_engine import UCIEngine, UCIEngineError

router = APIRouter()

ENGINE_BINARY_PATH = os.environ.get("SAPCHESS_ENGINE_PATH", "./sapchess")
SEARCH_DEPTH = int(os.environ.get("SAPCHESS_EXPLAIN_DEPTH", "12"))


class ExplainRequest(BaseModel):
    fen: str | None = Field(
        default=None,
        description="FEN of the position BEFORE the move. Defaults to the start position.",
    )
    move: str = Field(
        description="The move to explain, in UCI format, e.g. 'e2e4'."
    )


class ExplainResponse(BaseModel):
    move_san: str | None
    evaluation: str
    score_cp: int | None
    score_mate: int | None
    principal_variation: list[str]
    explanation: str


@router.post("/api/explain", response_model=ExplainResponse)
def explain_move(request: ExplainRequest) -> ExplainResponse:
    """
    Analyze `request.move` from `request.fen` and return an explanation.

    Runs the engine to get an evaluation and PV for the resulting
    position, then asks the LLM to explain the move in plain English
    (cached per position+move).
    """
    move_san = uci_move_to_san(request.fen, request.move)
    if move_san is None:
        raise HTTPException(status_code=400, detail="Illegal or unparseable move for given position")

    engine = UCIEngine(ENGINE_BINARY_PATH)
    try:
        engine.start()
        engine.set_position(fen=request.fen, moves=[request.move])
        result = engine.go(depth=SEARCH_DEPTH)
    except UCIEngineError as exc:
        raise HTTPException(status_code=500, detail=f"Engine error: {exc}") from exc
    finally:
        engine.quit()

    # Determine side to move *after* the played move, for score perspective.
    side_to_move_white = _white_to_move_after(request.fen, request.move)

    evaluation = score_to_readable(result.score_cp, result.score_mate, side_to_move_white)
    post_move_fen = _fen_after_move(request.fen, request.move)
    pv_san = pv_to_san(post_move_fen, result.pv, max_moves=5)

    fen_before = request.fen or _START_FEN
    explanation = _get_explanation(
        fen_before=fen_before,
        move_san=move_san,
        move_uci=request.move,
        evaluation=evaluation,
        pv_san=pv_san,
    )

    return ExplainResponse(
        move_san=move_san,
        evaluation=evaluation,
        score_cp=result.score_cp,
        score_mate=result.score_mate,
        principal_variation=pv_san,
        explanation=explanation,
    )


_START_FEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"

# Shown to the user when the LLM call fails or is not configured, so the
# rest of the response (evaluation, PV) is still useful.
_FALLBACK_EXPLANATION = (
    "Explanation unavailable right now, but the evaluation and "
    "engine line above still reflect the position accurately."
)


def _get_explanation(
    fen_before: str,
    move_san: str,
    move_uci: str,
    evaluation: str,
    pv_san: list[str],
) -> str:
    """
    Return an explanation for the move, using the cache if available,
    otherwise calling the LLM and caching the result.

    Falls back to a generic message (without raising) if the LLM is
    unconfigured or the API call fails, so a missing API key doesn't
    break the whole endpoint.
    """
    cached = cache.get(fen_before, move_uci)
    if cached is not None:
        return cached

    prompt = build_explanation_prompt(
        fen_before=fen_before,
        move_san=move_san,
        evaluation=evaluation,
        principal_variation=pv_san,
    )

    try:
        explanation = generate_text(prompt, system=SYSTEM_PROMPT)
    except (LLMConfigError, LLMRequestError):
        return _FALLBACK_EXPLANATION

    if not explanation:
        return _FALLBACK_EXPLANATION

    cache.set(fen_before, move_uci, explanation)
    return explanation


def _fen_after_move(fen: str | None, move: str) -> str:
    """Return the FEN of the position after `move` is played from `fen`."""
    import chess

    board = chess.Board(fen) if fen else chess.Board()
    board.push_uci(move)
    return board.fen()


def _white_to_move_after(fen: str | None, move: str) -> bool:
    """Return True if it's White to move in the position after `move` is played."""
    import chess

    board = chess.Board(fen) if fen else chess.Board()
    board.push_uci(move)
    return board.turn == chess.WHITE
